// Generated by gencpp from file pranshul/gps_srv.msg
// DO NOT EDIT!


#ifndef PRANSHUL_MESSAGE_GPS_SRV_H
#define PRANSHUL_MESSAGE_GPS_SRV_H

#include <ros/service_traits.h>


#include <pranshul/gps_srvRequest.h>
#include <pranshul/gps_srvResponse.h>


namespace pranshul
{

struct gps_srv
{

typedef gps_srvRequest Request;
typedef gps_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gps_srv
} // namespace pranshul


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pranshul::gps_srv > {
  static const char* value()
  {
    return "14073e24f24eb0fa3a2263b266dbf3bc";
  }

  static const char* value(const ::pranshul::gps_srv&) { return value(); }
};

template<>
struct DataType< ::pranshul::gps_srv > {
  static const char* value()
  {
    return "pranshul/gps_srv";
  }

  static const char* value(const ::pranshul::gps_srv&) { return value(); }
};


// service_traits::MD5Sum< ::pranshul::gps_srvRequest> should match 
// service_traits::MD5Sum< ::pranshul::gps_srv > 
template<>
struct MD5Sum< ::pranshul::gps_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pranshul::gps_srv >::value();
  }
  static const char* value(const ::pranshul::gps_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pranshul::gps_srvRequest> should match 
// service_traits::DataType< ::pranshul::gps_srv > 
template<>
struct DataType< ::pranshul::gps_srvRequest>
{
  static const char* value()
  {
    return DataType< ::pranshul::gps_srv >::value();
  }
  static const char* value(const ::pranshul::gps_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pranshul::gps_srvResponse> should match 
// service_traits::MD5Sum< ::pranshul::gps_srv > 
template<>
struct MD5Sum< ::pranshul::gps_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pranshul::gps_srv >::value();
  }
  static const char* value(const ::pranshul::gps_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pranshul::gps_srvResponse> should match 
// service_traits::DataType< ::pranshul::gps_srv > 
template<>
struct DataType< ::pranshul::gps_srvResponse>
{
  static const char* value()
  {
    return DataType< ::pranshul::gps_srv >::value();
  }
  static const char* value(const ::pranshul::gps_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRANSHUL_MESSAGE_GPS_SRV_H
